name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python versions
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
            
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      - name: Test with pytest
        run: pytest --cov=. --cov-report=xml --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml tests.py
 
      # Install Coverage Badge Extension
     # - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
      # if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      #  uses: we-cli/coverage-badge-action@main
      
      # Install Coverage Badge Extension
      - name: Update Coverage Badge
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Set this in your repository secrets
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
      
      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
