name: Pylint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
        
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python # Set Python Version
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
        
      - name: Install Pyflakes
        run: |
          python -m pip install --upgrade pip
          pip install pyflakes'
      - name: Run Pyflakes
        run: |
          find . -name '*.py' -exec pylint {} \;
