name: Pyflakes

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyflakes
    - name: Run pyflakes
      run: |
        pyflakes your_module > pyflakes-report.txt || true
        if [ -s pyflakes-report.txt ]; then
          cat pyflakes-report.txt
          exit 1
        fi
        
